version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 12
    labels:
      - dependabot
    assignees:
      - "SteinRobert"
